### ISSUE TITLE
Is this solution still working for anyone?

### ISSUE THREAD

**Issue by ovizii** [songchenwen/plexdlnaplayer#20]
plexdlnaplayer has stopped working for me :-( could anyone still using it confirm whether it still works for them, so I know if it's something in my ecosystem which stopped working. 

it runs just fine, I can access its web interface and still see my dlna speaker still properly connected/linked but when opening plexamp I do no longer see it as a casting target.

I'm unaware of anything major having changed in my network except plex and plexamp got updates.

**Comment by rockstar2020** [comment]
Hi @ovizii,
I just installed it yesterday and I can confirm it's working.
FYI I installed it in a docker running on Ubuntu 23.04.
The only issue though is that sometimes it doesn't automatically play the next track in a playlist.
Sometimes it just doesn't play the next track and I have to manually play it.
Not a perfect solution but surely it's almost there.

**Comment by ovizii** [comment]
Thanks for confirming. I admit I forgot to update my post: 

Somehow my instance only started working again once I deleted its configuration file and paired everything again.
