### ISSUE TITLE
gapless support?

### ISSUE THREAD

**Issue by psmelion** [songchenwen/plexdlnaplayer#9]
Thanks for the great work! Just tried this and it actually works! Tested streaming from 44.1 to 192khz and DSD64/128 and even MQA works! Great job!!!

The only thing missing is gapless playback between tracks. Could it be possible to add gapless playback? Or is there something I can edit in adapters.py to enable the function?

Thanks!

**Comment by songchenwen** [comment]
I'm afraid this is not possible. The DLNA receiver plays the file from Plex server directly, Plex app is only acting as a controller and this project is a translator between Plex protocol and DLNA. IMHO, gapless playback needs another decoding and re-encoding layer.
